stages:
  - docker-setup
  - docker-clean
  - build
  - test

build-job:
  image: docker:stable
  stage: build
  tags:
     - docker-build
  script:
    - make all-dev
    
#cypress-test-job:
#  stage: test
#  tags:
#    - docker-build
#  script:
#    - make test

