stages:
  - docker-setup
  - build
  - test

image: docker:stable

services:
  - docker:dind

docker-setup:
  tags:
    - docker-build
  stage: docker-setup
  script:
    - docker --version
    - docker images --all
    - echo "Starting docker"
    - docker run hello-world
    - echo "Docker is up"

build-job:
  tags:
    - docker-build
  stage: build
  script:
    - make all
    - make run
    
cypress-job:
  stage: test
  image: cypress/included:9.1.1
  script:
    - echo "CI_REGISTRY_IMAGE is $CI_REGISTRY_IMAGE"
    - sleep 10 # Wait for the application to initialize
    - npx cypress run --config baseUrl=http://localhost:3000

