stages:
  - build
  - test

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - make all
    - make run

cypress_tests:
  stage: test
  image: cypress/included:latest
  script:
    - npm install --save-dev cypress
    - $(npm bin)/cypress verify
    - $(npm bin)/cypress run --config baseUrl=http://localhost:3000
  dependencies:
    - build-job