stages:
  - docker-setup
  - build
  - test

docker-setup:
  tags:
    - docker-build
  stage: docker-setup
  script:
    - docker --version
    - docker images --all
    - echo "Starting docker"
    - docker run hello-world
    - echo "Docker is up"

build-job:
  stage: build
  image: docker:stable
  tags:
    - docker-build
  services:
    - docker:dind
  script:
    - make all
    - make run
    
cypress-test-job:
  stage: test
  image: cypress/included:9.1.1
  tags:
     - docker-build
  services:
    - docker:dind
  script:
    - echo "CI_REGISTRY_IMAGE is $CI_REGISTRY_IMAGE"
    - docker pull $CI_REGISTRY_IMAGE
    - docker run -d -p 3000:3000 $CI_REGISTRY_IMAGE
    - sleep 10 # Wait for the application to initialize
    - npx cypress run --config baseUrl=http://localhost:3000

