image: cypress/browsers:node14.17.0-chrome88-ff89

stages:
  - test

before_script:
  # Install dependencies, assuming your project has a package.json
  # You might need to adjust commands depending on your project setup
  - npm install

test:
  stage: test
  script:
    # Run Cypress tests
    - $(npm bin)/cypress run
  only:
    - master
