image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - docker build -t my-app .

test:
  stage: test
  script:
    - docker run --name my-app-container -d my-app
    - docker exec my-app-container npm run test:cypress
  only:
    - master
