stages:
  - build
  - test

image: docker:stable

services:
  - docker:dind

build-job:
  stage: build
  tags:
    - docker-build
  script:
    - make all
    - make run
    
cypress-test-job:
  stage: test
  image: cypress/included:9.1.1
  tags:
    - docker-build
  script:
    - cypress run
