stages:
  - docker-setup
  - build
  - test

docker-setup:
  tags:
    - docker-build
  stage: docker-setup
  script:
    - docker system prune -f
    - docker --version
    - docker images --all
    - echo "Starting docker"
    - docker run hello-world
    - echo "Docker is up"


build-job:
  stage: build
  image: docker:stable
  tags:
    - docker-build
  services:
    - docker:dind
  script:
    - make all
    - make run
    
cypress-test-job:
  stage: test
  tags:
     - docker-build
  script:
    - docker run -w /e2e -v $(pwd):/e2e --entrypoint cypress cypress/included:9.1.1 verify
    - docker run -w /e2e -v $(pwd):/e2e --entrypoint cypress cypress/included:9.1.1 run --config baseUrl=http://localhost:3000


