stages:
  - build
  - test
services:
  - docker:dind
build-job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

cypress-test-job:
  stage: test
  image: cypress/included:9.1.1
  services:
    - docker:dind
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run -d -p 3000:3000 $CI_REGISTRY_IMAGE
    - sleep 10 # Wait for the application to initialize
    - npx cypress run --config baseUrl=http://localhost:3000

