stages:
  - docker-setup
  - docker-clean
  - build
  - test

image: docker:stable

docker-setup:
  tags:
    - docker-build
  stage: docker-setup
  services:
    - docker:dind
  script:
    - docker --version
    - docker images --all
    - echo "Starting docker"
    - docker run hello-world
    - echo "Docker is up"

docker-clean:
  stage: docker-clean
  services:
    - docker:dind
  script:
    - docker ps -a -q -f status=exited | xargs --no-run-if-empty docker rm -v
    - docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi
    - docker volume ls -qf dangling=true | xargs --no-run-if-empty docker volume rm

build-job:
  stage: build
  tags:
    - docker-build
  services:
    - docker:dind
  script:
    - make all
    - make run
    
cypress-test-job:
  stage: test
  tags:
     - docker-build
  script:
    - docker run -w /e2e -v $(pwd):/e2e --entrypoint cypress cypress/included:9.1.1 verify
    - docker run -w /e2e -v $(pwd):/e2e --entrypoint cypress cypress/included:9.1.1 run --config baseUrl=http://localhost:3000


