version: "3.8"
services:
  frontenddev:
    image: frontenddev
    ports:
      - 3000:3000
    volumes:
      - ./Containers/FrontEnd/src:/app/src

  assethandler:
    image: assethandler
    ports:
      - "8080:8080"

  networkscan:
    image: networkscan
    ports:
      - "8081:8081"

  confighandler:
    image: confighandler
    ports:
      - "3001:3001"
    volumes:
      - ./Containers/ConfigHandler/src:/app/src

  netscanstorage:
    image: mongo
    restart: always
    command: [ "mongod", "--port", "27019", "--quiet", "--syslog" ]
    ports:
      - "27019:27019"
    expose:
      - "27019"
    volumes:
      - netscanstorage:/data/db
      - netscanconfig:/data/configdb

  dbstorage:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - dbstorage:/data/db
      - dbconfig:/data/configdb

  configstorage:
    image: mongo
    restart: always
    command: [ "mongod", "--port", "27018", "--quiet", "--syslog" ]
    ports:
      - "27018:27018"
    expose:
      - "27018"
    volumes:
      - configstorage:/data/db
      - configdbconfig:/data/configdb

  keycloakstorage:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak_local
    ports:
      - "8085:8085"
      - "8443:8443"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakstorage:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin # makeTheDevelopersLifesH4RDbySettingAwaytoLongPassword!
    depends_on:
      - keycloakstorage

volumes:
  configstorage:
  configdbconfig:
  dbstorage:
  dbconfig:
  netscanstorage:
  netscanconfig:
  keycloak_data:


networks:
  test_network:
    driver: bridge
