version: "3.8"
services:
  frontenddev:
    image: frontenddev
    ports:
      - 3000:3000
    volumes:
      - ./Containers/FrontEnd/src:/app/src

  assethandler:
    image: assethandler
    ports:
      - "8080:8080"

  networkscan:
    image: networkscan
    ports:
      - "8081:8081"

  confighandler:
    image: confighandler
    ports:
      - "3001:3001"
    volumes:
      - ./Containers/ConfigHandler/src:/app/src

  dbstorage:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - dbstorage:/data/db
      - dbconfig:/data/configdb

  configstorage:
    image: mongo
    restart: always
    command: [ "mongod", "--port", "27018", "--quiet", "--syslog" ]
    ports:
      - "27018:27018"
    expose:
      - "27018"
    volumes:
      - configstorage:/data/db
      - configdbconfig:/data/configdb

volumes:
  configstorage:
  configdbconfig:
  dbstorage:
  dbconfig:


networks:
  test_network:
    driver: bridge
