version: "3.8"
services:
  frontenddev:
    image: frontenddev
    ports:
      - 3000:3000
    volumes:
      - ./Containers/FrontEnd/src:/app/src
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224 # TODO: Use fluentd's DNS name.
        tag: frontenddev.app
    depends_on:
      fluentd:
        condition: service_healthy

  assethandler:
    image: assethandler
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224 # TODO: Use fluentd's DNS name.
        tag: assethandler.app
    depends_on:
      fluentd:
        condition: service_healthy

  networkscan:
    image: networkscan
    ports:
      - "8081:8081"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224 # TODO: Use fluentd's DNS name.
        tag: networkscan.app
    depends_on:
      fluentd:
        condition: service_healthy

  confighandler:
    image: confighandler
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./Containers/ConfigHandler/src:/app/src
    depends_on:
      - keycloak

  cyclonedx:
    image: cyclonedx
    ports:
      - "8082:8082"

  cvescanner:
    image: cvescanner
    volumes:
      - ./Containers/CVEScanner/src:/app/src
    ports:
      - "3002:3002"
    # env_file:
    #   - ./Containers/CVEScanner/.env

  netscanstorage:
    image: mongo
    restart: always
    command: [ "mongod", "--port", "27019", "--quiet", "--syslog" ]
    ports:
      - "27019:27019"
    expose:
      - "27019"
    volumes:
      - netscanstorage:/data/db
      - netscanconfig:/data/configdb

  dbstorage:
    image: mongo
    restart: always
    command: --quiet --syslog
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224 # TODO: Use fluentd's DNS name.
        tag: dbstorage.app
    depends_on:
      fluentd:
        condition: service_healthy
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - dbstorage:/data/db
      - dbconfig:/data/configdb

  configstorage:
    image: mongo
    restart: always
    command: [ "mongod", "--port", "27018", "--quiet", "--syslog" ]
    ports:
      - "27018:27018"
    expose:
      - "27018"
    volumes:
      - configstorage:/data/db
      - configdbconfig:/data/configdb

  cyclonedxstorage:
    image: mongo
    restart: always
    command: [ "mongod", "--port", "27020", "--quiet", "--syslog" ]
    ports:
      - "27020:27020"
    expose:
      - "27020"
    volumes:
      - cyclonedxstorage:/data/db
      - cyclonedxconfig:/data/configdb

  keycloakstorage:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak_local
    ports:
      - "8085:8085"
      - "8443:8443"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakstorage:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin # makeTheDevelopersLifesH4RDbySettingAwaytoLongPassword!
      KC_HEALTH_ENABLED: true
    depends_on:
      - keycloakstorage

  clientinit:
    image: clientinit
    depends_on:
      - keycloak

  authhandler:
    image: authhandler
    volumes:
      - ./Containers/AuthHandler/src:/app/src
    depends_on:
      - keycloak

  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material
    restart: always
    ports:
      - "6880:8000"
    volumes:
      - "./Containers/docs:/docs:ro"

  fluentd:
    image: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    healthcheck:
      test: [ "CMD", "netstat", "-tuln", "|", "grep", "24224" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 3G
    # TODO: Ticket I032, Replace later with proper key management
    # environment:

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:5601/api/status || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    # TODO: Ticket I032, Replace later with proper key management
    # environment:
    #   - KIBANAPASSWORD=$KIBANAPASSWORD

volumes:
  configstorage:
  configdbconfig:
  dbstorage:
  dbconfig:
  netscanstorage:
  netscanconfig:
  keycloak_data:
  cyclonedxstorage:
  cyclonedxconfig:

networks:
  test_network:
    driver: bridge
