version: "3.8"
services:
  assinvfront:
    image: assinvfront
    ports:
      - 3000:3000
      - 85:85
    volumes:
      - ./Containers/FrontEnd/src:/app/src

  assethandler:
    image: assethandler
    ports:
      - 8092:8092

  networkscan:
    image: networkscan
    ports:
      - 8081:8081

  dbstorage:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - dbstorage:/data/db
      - dbconfig:/data/configdb

volumes:
  dbstorage:
  dbconfig:
