@startuml "MicroServices"
allow_mixing

node browser
node FrontEnd

frame "Micro Services" {

  class AssetHandeler {
    ..Methods..
    + SaveState()
    + GetState()
    + EditState()
    + DeleteState()
  }

  class NetworkScan {
    ..Methods..
    + ScanNetwork()
    + ParseScan()
    + SendScan()
  }

  class SBOMhandler {
    ..Methods..
    + performCVEscan()
    + saveSBOMlibraries()
    + updateSBOMlibraries()
  }

  class configHandler {
  ..Methods..
    + saveUserSettings()
    + updateUserSettings()
    + saveDocumentation()
    + updateDocumentation()
    + saveTrelloIssueBoard()
    + updateTrelloIssueBoard()
    + performRecurringScan()
  }

  class authHandler {
    ..Methods..
    + validateUser()
    + generateUsertoken()
  }

  database keycloak {

  }

  cloud EFKstack {
    cloud Kibana {

    }
    cloud Fluentd {

    }
    cloud Elastic {

    }
  }
}

cloud trelloAPI {

}

cloud OssCveAPI {

}

actor user
user --> browser : uses
note right of browser
    user <<User>> interacts
    with the system via browser
end note

browser <--> FrontEnd
FrontEnd <--> AssetHandeler : get latest state
FrontEnd <--> keycloak : user administration
FrontEnd <--> configHandler : user configurations
FrontEnd <--> trelloAPI
FrontEnd <--> SBOMhandler : upload SBOM file
FrontEnd <--> authHandler : authenticates

authHandler <--> keycloak : authenticates

configHandler <--> NetworkScan : Perform recurring scan
configHandler <--> SBOMhandler : Perform recurring scan

AssetHandeler <--> NetworkScan : check status

configHandler <--> OssCveAPI



@enduml
