# https://www.elastic.co/guide/en/kibana/current/settings.html

# Changed to latest version
FROM docker.elastic.co/kibana/kibana:8.12.1  

#### 
# TODO: Ticket I031, Implement TLS between elasticsearch and Kibana
#   - Use environmental variable for access keys and passwords
#   - usernames and default users
####

# TODO: Ticket I031, Volume mount elastic and kibana config
# COPY ./config/kibana.yml /usr/share/kibana/config/