
@startuml Goals
!include <archimate/Archimate>

Motivation_Goal("Customizable", "Customizable")
Motivation_Goal("Alwayscurrentinformation", "Always\ncurrent\ninformation")
Motivation_Goal("Presentrelevantinformation", "Present\nrelevant\ninformation")
Motivation_Goal("HighlyAvailable", "Highly\nAvailable")
Motivation_Goal("Enableriskbaseddecisionmaking", "Enable\nrisk\nbased\ndecision\nmaking")
Motivation_Goal("Resilient", "Resilient")
Motivation_Goal("RoleBasedAccess", "Role\nBased\nAccess")
Motivation_Goal("Efficientassetmanagement", "Efficient\nasset\nmanagement")
Motivation_Goal("Representdifferenttypesofassets", "Represent\ndifferent\ntypes\nof\nassets")
Motivation_Goal("Representdependenciesbetweenassets", "Represent\ndependencies\nbetween\nassets")
Motivation_Goal("Extendable", "Extendable")
Motivation_Goal("Secure", "Secure")
Motivation_Goal("UserFriendly", "User\nFriendly")
Motivation_Goal("SupportChangeManagement", "Support\nChange\nManagement")
Motivation_Goal("SupportRiskManagement", "Support\nRisk\nManagement")
Junction_And("UserFriendly_and", " ")
Rel_Association_dir("UserFriendly_and", "UserFriendly")
Rel_Association_dir("RoleBasedAccess", "UserFriendly_and")
Junction_And("Presentrelevantinformation_and", " ")
Rel_Association_dir("Presentrelevantinformation_and", "Presentrelevantinformation")
Rel_Association_dir("RoleBasedAccess", "Presentrelevantinformation_and")
Rel_Association_dir("Alwayscurrentinformation", "Presentrelevantinformation_and")
Rel_Association_dir("Representdependenciesbetweenassets", "Presentrelevantinformation_and")
Rel_Association_dir("Representdifferenttypesofassets", "Presentrelevantinformation_and")
Rel_Association_dir("Presentrelevantinformation", "UserFriendly_and")
Junction_And("Enableriskbaseddecisionmaking_and", " ")
Rel_Association_dir("Enableriskbaseddecisionmaking_and", "Enableriskbaseddecisionmaking")
Rel_Association_dir("Presentrelevantinformation", "Enableriskbaseddecisionmaking_and")
Junction_And("SupportRiskManagement_and", " ")
Rel_Association_dir("SupportRiskManagement_and", "SupportRiskManagement")
Rel_Association_dir("Enableriskbaseddecisionmaking", "SupportRiskManagement_and")
Junction_And("SupportChangeManagement_and", " ")
Rel_Association_dir("SupportChangeManagement_and", "SupportChangeManagement")
Rel_Association_dir("Enableriskbaseddecisionmaking", "SupportChangeManagement_and")
Rel_Association_dir("Customizable", "UserFriendly_and")
Rel_Association_dir("Extendable", "UserFriendly_and")
Junction_And("Secure_and", " ")
Rel_Association_dir("Secure_and", "Secure")
Rel_Association_dir("RoleBasedAccess", "Secure_and")
Rel_Association_dir("HighlyAvailable", "Secure_and")
Rel_Association_dir("Resilient", "Secure_and")
Junction_And("Efficientassetmanagement_and", " ")
Rel_Association_dir("Efficientassetmanagement_and", "Efficientassetmanagement")
Rel_Association_dir("Alwayscurrentinformation", "Efficientassetmanagement_and")
Rel_Association_dir("Representdifferenttypesofassets", "Efficientassetmanagement_and")
Rel_Association_dir("Customizable", "Efficientassetmanagement_and")
Rel_Association_dir("UserFriendly", "Efficientassetmanagement_and")
@enduml
    