
@startuml TitleFontStyle
skinparam archimate {
  StereotypeAlignment right
  DiagonalCorner<<business-actor>> 12
  DiagonalCorner<<motivation-outcome>> 12
  RoundCorner<<motivation-requirement>> 20
  DiagonalCorner<<motivation-constraint>> 10
  RoundCorner<<motivation-goal>> 20
}

!define Requirement(e_alias, e_label) archimate #green "<<requirement>>\n==e_label" <<motivation-requirement>> as e_alias
!define Goal(e_alias, e_label) archimate #green "<<goal>>\n==e_label" <<motivation-outcome>> as e_alias
!define UserGoal(e_alias, e_label) archimate #LightGreen "<<user goal>>\n==e_label" <<motivation-goal>> as e_alias
!define Task(e_alias, e_label) archimate #LightGreen "<<task>>\n==e_label" <<application-interface>> as e_alias
!define UseCase(e_alias, e_label) #LightBlue (<<use case>>\n==e_label) as e_alias
!define Obstacle(e_alias, e_label) archimate #DeepPink "<<obstacle>>\n==e_label" <<motivation-constraint>> as e_alias
!define Persona(e_alias, e_label) archimate #cadetBlue "<<persona>>\n==e_label" <<business-actor>> as e_alias
!define Role(e_alias, e_label) archimate #CadetBlue "<<role>>\n==e_label" <<business-role>> as e_alias
!define Asset(e_alias, e_label) archimate #CadetBlue "<<asset>>\n==e_label" <<strategy-resource>> as e_alias
!define Association(e_sourceAlias, e_targetAlias) e_sourceAlias -- e_targetAlias
!define Mitigates(e_sourceAlias, e_targetAlias) e_sourceAlias @--> e_targetAlias : "mitigates"
!define Obstructs(e_sourceAlias, e_targetAlias) e_sourceAlias <== e_targetAlias : "obstructs"
!define Relates(e_sourceAlias, e_targetAlias, e_linktype="relates\nto") e_sourceAlias ..> e_targetAlias : e_linktype
!define Refines(e_sourceAlias, e_targetAlias) e_sourceAlias <|-- e_targetAlias : "refines"
!define Cause(e_sourceAlias, e_targetAlias) e_sourceAlias <.. e_targetAlias : "mitigates"
!define Dependency(e_sourceAlias, e_targetAlias) e_sourceAlias *--|> e_targetAlias : "depends\non"
left to right direction

Goal("UserFriendly","User Friendly")
Goal("RoleBasedAccess", "Role Based Access")
Dependency("UserFriendly", "RoleBasedAccess")
Goal("Secure","Secure")
Dependency("Secure", "RoleBasedAccess")
Goal("Presentrelevantinformation","Present relevant information")
Dependency("Presentrelevantinformation", "RoleBasedAccess")
Goal("Alwayscurrentinformation", "Always current information")
Dependency("Presentrelevantinformation", "Alwayscurrentinformation")
Goal("SupportRiskManagement","Support Risk Management")
Goal("Enableriskbaseddecisionmaking", "Enable risk based decision making")
Dependency("SupportRiskManagement", "Enableriskbaseddecisionmaking")
Goal("SupportChangeManagement","Support Change Management")
Dependency("SupportChangeManagement", "Enableriskbaseddecisionmaking")
Goal("Customizable","Customizable")
Requirement("CI7Customassettypes", "CI7 - Custom asset types")
Refines("Customizable", "CI7Customassettypes")
Goal("Representdifferenttypesofassets","Represent different types of assets")
Requirement("CI2Assettypehierarchy", "CI2 - Asset type hierarchy")
Refines("Representdifferenttypesofassets", "CI2Assettypehierarchy")
Goal("Representdependenciesbetweenassets","Represent dependencies between assets")
Requirement("CI4Relationships", "CI4 - Relationships")
Refines("Representdependenciesbetweenassets", "CI4Relationships")
Requirement("INFO1Manualentries", "INFO-1 Manual entries")
Refines("Alwayscurrentinformation", "INFO1Manualentries")
Requirement("INFO2Automaticinformationgathering", "INFO-2 Automatic information gathering")
Refines("Alwayscurrentinformation", "INFO2Automaticinformationgathering")
Requirement("INFO4AutomatedAssetdiscovery", "INFO-4 Automated Asset discovery")
Refines("Alwayscurrentinformation", "INFO4AutomatedAssetdiscovery")
Goal("Extendable","Extendable")
Refines("Extendable", "CI2Assettypehierarchy")
Refines("Extendable", "CI7Customassettypes")
Requirement("ARCH2Plugins", "ARCH-2 Plugins")
Refines("Extendable", "ARCH2Plugins")
Goal("HighlyAvailable","Highly Available")
Requirement("ARCH1113ThreadSafe", "ARCH-1.11.3 Thread Safe")
Refines("HighlyAvailable", "ARCH1113ThreadSafe")
Requirement("AUTH1LocalUserDatabase", "AUTH-1 Local User Database")
Refines("HighlyAvailable", "AUTH1LocalUserDatabase")
Requirement("AUTH2Remoteuserdatabase", "AUTH-2 Remote user database")
Refines("HighlyAvailable", "AUTH2Remoteuserdatabase")
Requirement("INFO3LocalDatastore", "INFO-3 Local Data store")
Refines("HighlyAvailable", "INFO3LocalDatastore")
Goal("Resilient","Resilient")
Requirement("AUTH3Priorityofuserdatabases", "AUTH-3 Priority of user databases")
Refines("Resilient", "AUTH3Priorityofuserdatabases")
Refines("Resilient", "INFO3LocalDatastore")
Refines("Resilient", "AUTH1LocalUserDatabase")
Requirement("ARCH123AuthenticationMechanism", "ARCH-1.2.3 Authentication Mechanism")
Refines("RoleBasedAccess", "ARCH123AuthenticationMechanism")
Requirement("ARCH144AccessControlMechanism", "ARCH-1.4.4 Access Control Mechanism")
Refines("RoleBasedAccess", "ARCH144AccessControlMechanism")
Obstacle("A01BrokenAccessControl","A01 – Broken Access Control")
Requirement("ARCH141AccessEnforcementPoints", "ARCH-1.4.1 Access Enforcement Points")
Cause("A01BrokenAccessControl", "ARCH141AccessEnforcementPoints")
Cause("A01BrokenAccessControl", "ARCH144AccessControlMechanism")
Obstacle("A07IdentificationandAuthenticationFailures","A07 – Identification and Authentication Failures")
Cause("A07IdentificationandAuthenticationFailures", "ARCH123AuthenticationMechanism")
Requirement("ARCH124Authenticationpaths", "ARCH-1.2.4 Authentication paths")
Cause("A07IdentificationandAuthenticationFailures", "ARCH124Authenticationpaths")
Obstacle("A08SoftwareandDataIntegrityFailures","A08 – Software and Data Integrity Failures")
Requirement("ARCH152Serialization", "ARCH-1.5.2 Serialization")
Cause("A08SoftwareandDataIntegrityFailures", "ARCH152Serialization")
Requirement("ARCH153Inputvalidation", "ARCH-1.5.3 Input validation")
Cause("A08SoftwareandDataIntegrityFailures", "ARCH153Inputvalidation")
Requirement("ARCH111SDLC", "ARCH-1.1.1 SDLC")
Cause("A08SoftwareandDataIntegrityFailures", "ARCH111SDLC")
Obstacle("A09SecurityLoggingandMonitoringFailures","A09 – Security Logging and Monitoring Failures")
Requirement("ARCH171Logging", "ARCH-1.7.1 Logging")
Cause("A09SecurityLoggingandMonitoringFailures", "ARCH171Logging")
Obstacle("A04InsecureDesign","A04 – Insecure Design")
Requirement("ARCH116DesignandArchitectSecurityIn", "ARCH-1.1.6 Design and Architect Security In")
Cause("A04InsecureDesign", "ARCH116DesignandArchitectSecurityIn")
Requirement("ARCH113FeaturesandUserstories", "ARCH-1.1.3 Features and User stories")
Cause("A04InsecureDesign", "ARCH113FeaturesandUserstories")
Requirement("ARCH112Threatmodeling", "ARCH-1.1.2 Threat modeling")
Cause("A04InsecureDesign", "ARCH112Threatmodeling")
Obstacle("A06VulnerableandOutdatedComponents","A06 – Vulnerable and Outdated Components")
Cause("A06VulnerableandOutdatedComponents", "ARCH111SDLC")
Obstacle("A03Injection","A03 – Injection")
Cause("A03Injection", "ARCH153Inputvalidation")
Requirement("ARCH154Outputencoding", "ARCH-1.5.4 Output encoding")
Cause("A03Injection", "ARCH154Outputencoding")
Obstacle("Externalsourcesunavailable","External sources unavailable")
Cause("Externalsourcesunavailable", "INFO3LocalDatastore")
Obstacle("A05SecurityMisconfiguration","A05 – Security Misconfiguration")
Cause("A05SecurityMisconfiguration", "ARCH111SDLC")
Obstacle("A02CryptographicFailures","A02 – Cryptographic Failures")
Requirement("ARCH162Keyprotection", "ARCH-1.6.2 Key protection")
Cause("A02CryptographicFailures", "ARCH162Keyprotection")
Requirement("ARCH163Keyreplacement", "ARCH-1.6.3 Key replacement")
Cause("A02CryptographicFailures", "ARCH163Keyreplacement")
UseCase("GenerateReports", "Generate Reports")
Refines("Customizable", "GenerateReports")
UseCase("AddNewAssettoInventory", "Add New Asset to Inventory")
Refines("Representdifferenttypesofassets", "AddNewAssettoInventory")
UseCase("SupportArchitecturalDecisions", "Support Architectural Decisions")
Refines("Representdifferenttypesofassets", "SupportArchitecturalDecisions")
Refines("Representdependenciesbetweenassets", "AddNewAssettoInventory")
UseCase("ManageAsset", "Manage Asset")
Refines("Alwayscurrentinformation", "ManageAsset")
UseCase("LifecycleManagement", "Lifecycle Management")
Refines("Alwayscurrentinformation", "LifecycleManagement")
UseCase("VulnerabilityManagement", "Vulnerability Management")
Refines("Alwayscurrentinformation", "VulnerabilityManagement")
Refines("Alwayscurrentinformation", "SupportArchitecturalDecisions")
Refines("Presentrelevantinformation", "GenerateReports")
UseCase("IncidentResponse", "Incident Response")
Refines("Presentrelevantinformation", "IncidentResponse")
Refines("Presentrelevantinformation", "SupportArchitecturalDecisions")
Refines("Extendable", "ManageAsset")
Refines("Extendable", "GenerateReports")
Refines("HighlyAvailable", "IncidentResponse")
UseCase("ImpactAnalysis", "Impact Analysis")
Refines("Enableriskbaseddecisionmaking", "ImpactAnalysis")
UseCase("Determineriskexposure", "Determine risk exposure")
Refines("Enableriskbaseddecisionmaking", "Determineriskexposure")
Refines("Enableriskbaseddecisionmaking", "SupportArchitecturalDecisions")
Refines("Resilient", "IncidentResponse")
UseCase("Managechanges", "Manage changes")
Refines("SupportChangeManagement", "Managechanges")
Refines("SupportRiskManagement", "Determineriskexposure")
Refines("SupportRiskManagement", "ImpactAnalysis")
Refines("SupportRiskManagement", "VulnerabilityManagement")
Goal("AssetOwner", "Asset Owner")
Refines("Alwayscurrentinformation", "AssetOwner")
Goal("RiskManager", "Risk Manager")
Refines("SupportRiskManagement", "RiskManager")
Goal("ITOperations", "IT Operations")
Refines("HighlyAvailable", "ITOperations")
Goal("ChangeManager", "Change Manager")
Refines("SupportChangeManagement", "ChangeManager")
Obstructs("Secure", "A01BrokenAccessControl")
Obstructs("Secure", "A08SoftwareandDataIntegrityFailures")
Obstructs("Secure", "A09SecurityLoggingandMonitoringFailures")
Obstructs("Secure", "A04InsecureDesign")
Obstructs("Secure", "A06VulnerableandOutdatedComponents")
Obstructs("Secure", "A03Injection")
Obstructs("Customizable", "A08SoftwareandDataIntegrityFailures")
Obstructs("Extendable", "A08SoftwareandDataIntegrityFailures")
Obstructs("Secure", "A05SecurityMisconfiguration")
Obstructs("Secure", "A02CryptographicFailures")
Obstacle("A10ServerSideRequestForgery", "A10 - Server-Side Request Forgery")
Obstructs("Secure", "A10ServerSideRequestForgery")
Obstacle("Informationnotsufficient", "Information not sufficient")
Obstructs("Enableriskbaseddecisionmaking", "Informationnotsufficient")
Obstacle("Informationoutdated", "Information outdated")
Obstructs("Enableriskbaseddecisionmaking", "Informationoutdated")
Obstacle("Unauthorizedchangestoassetinformation", "Unauthorized changes to asset information")
Obstructs("Alwayscurrentinformation", "Unauthorizedchangestoassetinformation")
Obstructs("Alwayscurrentinformation", "Externalsourcesunavailable")
Obstacle("Lossofinfrastructure", "Loss of infrastructure")
Obstructs("HighlyAvailable", "Lossofinfrastructure")
Cause("Externalsourcesunavailable", "Resilient")
Cause("Informationnotsufficient", "Representdependenciesbetweenassets")
Cause("Informationnotsufficient", "Representdifferenttypesofassets")
Cause("Informationnotsufficient", "Presentrelevantinformation")
Cause("Informationoutdated", "Alwayscurrentinformation")
Obstacle("Accesstosensitiveassetinformation", "Access to sensitive asset information")
Dependency("A01BrokenAccessControl", "Accesstosensitiveassetinformation")
Dependency("A01BrokenAccessControl", "Unauthorizedchangestoassetinformation")
Dependency("A01BrokenAccessControl", "A07IdentificationandAuthenticationFailures")
Dependency("A09SecurityLoggingandMonitoringFailures", "A07IdentificationandAuthenticationFailures")
Dependency("Externalsourcesunavailable", "Lossofinfrastructure")
@enduml