
@startuml Goals
!include <archimate/Archimate>

Motivation_Constraint("Informationoutdated", "Information\noutdated")
Motivation_Constraint("Unauthorizedchangestoassetinformation", "Unauthorized\nchanges\nto\nasset\ninformation")
Motivation_Constraint("A08SoftwareandDataIntegrityFailures", "A08\n–\nSoftware\nand\nData\nIntegrity\nFailures")
Motivation_Constraint("Informationnotsufficient", "Information\nnot\nsufficient")
Motivation_Constraint("Externalsourcesunavailable", "External\nsources\nunavailable")
Motivation_Constraint("Lossofinfrastructure", "Loss\nof\ninfrastructure")
Motivation_Constraint("Accesstosensitiveassetinformation", "Access\nto\nsensitive\nasset\ninformation")
Motivation_Constraint("A02CryptographicFailures", "A02\n–\nCryptographic\nFailures")
Motivation_Constraint("A09SecurityLoggingandMonitoringFailures", "A09\n–\nSecurity\nLogging\nand\nMonitoring\nFailures")
Motivation_Constraint("A01BrokenAccessControl", "A01\n–\nBroken\nAccess\nControl")
Motivation_Constraint("A07IdentificationandAuthenticationFailures", "A07\n–\nIdentification\nand\nAuthentication\nFailures")
Motivation_Constraint("A03Injection", "A03\n–\nInjection")
Motivation_Constraint("A04InsecureDesign", "A04\n–\nInsecure\nDesign")
Motivation_Constraint("A05SecurityMisconfiguration", "A05\n–\nSecurity\nMisconfiguration")
Motivation_Constraint("A06VulnerableandOutdatedComponents", "A06\n–\nVulnerable\nand\nOutdated\nComponents")
Motivation_Constraint("A10ServerSideRequestForgery", "A10\n-\nServer-Side\nRequest\nForgery")
Motivation_Requirement("ARCH141AccessEnforcementPoints", "ARCH-1.4.1\nAccess\nEnforcement\nPoints")
Junction_Or("A01BrokenAccessControl_resolve", " ")
Rel_Association_dir("A01BrokenAccessControl_resolve", "A01BrokenAccessControl")
Rel_Association_dir("ARCH141AccessEnforcementPoints", "A01BrokenAccessControl_resolve")
Motivation_Requirement("ARCH144AccessControlMechanism", "ARCH-1.4.4\nAccess\nControl\nMechanism")
Rel_Association_dir("ARCH144AccessControlMechanism", "A01BrokenAccessControl_resolve")
Motivation_Requirement("ARCH123AuthenticationMechanism", "ARCH-1.2.3\nAuthentication\nMechanism")
Junction_Or("A07IdentificationandAuthenticationFailures_resolve", " ")
Rel_Association_dir("A07IdentificationandAuthenticationFailures_resolve", "A07IdentificationandAuthenticationFailures")
Rel_Association_dir("ARCH123AuthenticationMechanism", "A07IdentificationandAuthenticationFailures_resolve")
Motivation_Requirement("ARCH124Authenticationpaths", "ARCH-1.2.4\nAuthentication\npaths")
Rel_Association_dir("ARCH124Authenticationpaths", "A07IdentificationandAuthenticationFailures_resolve")
Motivation_Requirement("ARCH152Serialization", "ARCH-1.5.2\nSerialization")
Junction_Or("A08SoftwareandDataIntegrityFailures_resolve", " ")
Rel_Association_dir("A08SoftwareandDataIntegrityFailures_resolve", "A08SoftwareandDataIntegrityFailures")
Rel_Association_dir("ARCH152Serialization", "A08SoftwareandDataIntegrityFailures_resolve")
Motivation_Requirement("ARCH153Inputvalidation", "ARCH-1.5.3\nInput\nvalidation")
Rel_Association_dir("ARCH153Inputvalidation", "A08SoftwareandDataIntegrityFailures_resolve")
Motivation_Requirement("ARCH111SDLC", "ARCH-1.1.1\nSDLC")
Rel_Association_dir("ARCH111SDLC", "A08SoftwareandDataIntegrityFailures_resolve")
Motivation_Requirement("ARCH171Logging", "ARCH-1.7.1\nLogging")
Junction_Or("A09SecurityLoggingandMonitoringFailures_resolve", " ")
Rel_Association_dir("A09SecurityLoggingandMonitoringFailures_resolve", "A09SecurityLoggingandMonitoringFailures")
Rel_Association_dir("ARCH171Logging", "A09SecurityLoggingandMonitoringFailures_resolve")
Motivation_Requirement("ARCH116DesignandArchitectSecurityIn", "ARCH-1.1.6\nDesign\nand\nArchitect\nSecurity\nIn")
Junction_Or("A04InsecureDesign_resolve", " ")
Rel_Association_dir("A04InsecureDesign_resolve", "A04InsecureDesign")
Rel_Association_dir("ARCH116DesignandArchitectSecurityIn", "A04InsecureDesign_resolve")
Motivation_Requirement("ARCH113FeaturesandUserstories", "ARCH-1.1.3\nFeatures\nand\nUser\nstories")
Rel_Association_dir("ARCH113FeaturesandUserstories", "A04InsecureDesign_resolve")
Motivation_Requirement("ARCH112Threatmodeling", "ARCH-1.1.2\nThreat\nmodeling")
Rel_Association_dir("ARCH112Threatmodeling", "A04InsecureDesign_resolve")
Junction_Or("A06VulnerableandOutdatedComponents_resolve", " ")
Rel_Association_dir("A06VulnerableandOutdatedComponents_resolve", "A06VulnerableandOutdatedComponents")
Rel_Association_dir("ARCH111SDLC", "A06VulnerableandOutdatedComponents_resolve")
Junction_Or("A03Injection_resolve", " ")
Rel_Association_dir("A03Injection_resolve", "A03Injection")
Rel_Association_dir("ARCH153Inputvalidation", "A03Injection_resolve")
Motivation_Requirement("ARCH154Outputencoding", "ARCH-1.5.4\nOutput\nencoding")
Rel_Association_dir("ARCH154Outputencoding", "A03Injection_resolve")
Motivation_Requirement("INFO3LocalDatastore", "INFO-3\nLocal\nData\nstore")
Junction_Or("Externalsourcesunavailable_resolve", " ")
Rel_Association_dir("Externalsourcesunavailable_resolve", "Externalsourcesunavailable")
Rel_Association_dir("INFO3LocalDatastore", "Externalsourcesunavailable_resolve")
Junction_Or("A05SecurityMisconfiguration_resolve", " ")
Rel_Association_dir("A05SecurityMisconfiguration_resolve", "A05SecurityMisconfiguration")
Rel_Association_dir("ARCH111SDLC", "A05SecurityMisconfiguration_resolve")
Motivation_Requirement("ARCH162Keyprotection", "ARCH-1.6.2\nKey\nprotection")
Junction_Or("A02CryptographicFailures_resolve", " ")
Rel_Association_dir("A02CryptographicFailures_resolve", "A02CryptographicFailures")
Rel_Association_dir("ARCH162Keyprotection", "A02CryptographicFailures_resolve")
Motivation_Requirement("ARCH163Keyreplacement", "ARCH-1.6.3\nKey\nreplacement")
Rel_Association_dir("ARCH163Keyreplacement", "A02CryptographicFailures_resolve")
Motivation_Goal("Alwayscurrentinformation", "Always\ncurrent\ninformation")
Rel_Influence("Unauthorizedchangestoassetinformation", "Alwayscurrentinformation", "Obstructs")
Rel_Influence("Externalsourcesunavailable", "Alwayscurrentinformation", "Obstructs")
Motivation_Goal("HighlyAvailable", "Highly\nAvailable")
Rel_Influence("Lossofinfrastructure", "HighlyAvailable", "Obstructs")
Motivation_Goal("Enableriskbaseddecisionmaking", "Enable\nrisk\nbased\ndecision\nmaking")
Rel_Influence("Informationnotsufficient", "Enableriskbaseddecisionmaking", "Obstructs")
Rel_Influence("Informationoutdated", "Enableriskbaseddecisionmaking", "Obstructs")
Motivation_Goal("Customizable", "Customizable")
Rel_Influence("A08SoftwareandDataIntegrityFailures", "Customizable", "Obstructs")
Motivation_Goal("Extendable", "Extendable")
Rel_Influence("A08SoftwareandDataIntegrityFailures", "Extendable", "Obstructs")
Motivation_Goal("Secure", "Secure")
Rel_Influence("A01BrokenAccessControl", "Secure", "Obstructs")
Rel_Influence("A08SoftwareandDataIntegrityFailures", "Secure", "Obstructs")
Rel_Influence("A09SecurityLoggingandMonitoringFailures", "Secure", "Obstructs")
Rel_Influence("A04InsecureDesign", "Secure", "Obstructs")
Rel_Influence("A06VulnerableandOutdatedComponents", "Secure", "Obstructs")
Rel_Influence("A03Injection", "Secure", "Obstructs")
Rel_Influence("A05SecurityMisconfiguration", "Secure", "Obstructs")
Rel_Influence("A02CryptographicFailures", "Secure", "Obstructs")
Rel_Influence("A10ServerSideRequestForgery", "Secure", "Obstructs")
Motivation_Goal("Resilient", "Resilient")
Rel_Association_dir("Resilient", "Externalsourcesunavailable_resolve")
Motivation_Goal("Representdependenciesbetweenassets", "Represent\ndependencies\nbetween\nassets")
Junction_Or("Informationnotsufficient_resolve", " ")
Rel_Association_dir("Informationnotsufficient_resolve", "Informationnotsufficient")
Rel_Association_dir("Representdependenciesbetweenassets", "Informationnotsufficient_resolve")
Motivation_Goal("Representdifferenttypesofassets", "Represent\ndifferent\ntypes\nof\nassets")
Rel_Association_dir("Representdifferenttypesofassets", "Informationnotsufficient_resolve")
Junction_Or("Informationoutdated_resolve", " ")
Rel_Association_dir("Informationoutdated_resolve", "Informationoutdated")
Rel_Association_dir("Alwayscurrentinformation", "Informationoutdated_resolve")
Motivation_Goal("Presentrelevantinformation", "Present\nrelevant\ninformation")
Rel_Association_dir("Presentrelevantinformation", "Informationnotsufficient_resolve")
Junction_And("A01BrokenAccessControl_and", " ")
Rel_Association_dir("A01BrokenAccessControl_and", "A01BrokenAccessControl")
Rel_Association_dir("Accesstosensitiveassetinformation", "A01BrokenAccessControl_and")
Rel_Association_dir("Unauthorizedchangestoassetinformation", "A01BrokenAccessControl_and")
Rel_Association_dir("A07IdentificationandAuthenticationFailures", "A01BrokenAccessControl_and")
Junction_And("A09SecurityLoggingandMonitoringFailures_and", " ")
Rel_Association_dir("A09SecurityLoggingandMonitoringFailures_and", "A09SecurityLoggingandMonitoringFailures")
Rel_Association_dir("A07IdentificationandAuthenticationFailures", "A09SecurityLoggingandMonitoringFailures_and")
Junction_And("Externalsourcesunavailable_and", " ")
Rel_Association_dir("Externalsourcesunavailable_and", "Externalsourcesunavailable")
Rel_Association_dir("Lossofinfrastructure", "Externalsourcesunavailable_and")
@enduml
    