
@startuml Goals
!include <archimate/Archimate>
left to right direction

Motivation_Requirement("CI1UniqueIdentifier", "=CI1\n-\nUnique\nIdentifier")
Motivation_Requirement("CI2Assettypehierarchy", "=CI2\n-\nAsset\ntype\nhierarchy")
Motivation_Requirement("CI3Attributes", "=CI3\n-\nAttributes")
Motivation_Requirement("CI4Relationships", "=CI4\n-\nRelationships")
Motivation_Requirement("CI5Mandatoryattributes", "=CI5\n-\nMandatory\nattributes")
Motivation_Requirement("CI7Customassettypes", "=CI7\n-\nCustom\nasset\ntypes")
Motivation_Requirement("AUTH2Remoteuserdatabase", "=AUTH-2\nRemote\nuser\ndatabase")
Motivation_Requirement("INFO4AutomatedAssetdiscovery", "=INFO-4\nAutomated\nAsset\ndiscovery")
Motivation_Requirement("INFO5DisableAutomaticInformationGathering", "=INFO-5\nDisable\nAutomatic\nInformation\nGathering")
Motivation_Requirement("CI6AuditLog", "=CI6\n-\nAudit\nLog")
Motivation_Requirement("AUTH1LocalUserDatabase", "=AUTH-1\nLocal\nUser\nDatabase")
Motivation_Requirement("INFO1Manualentries", "=INFO-1\nManual\nentries")
Motivation_Requirement("INFO2Automaticinformationgathering", "=INFO-2\nAutomatic\ninformation\ngathering")
Motivation_Requirement("INFO7Dataaccesscontrol", "=INFO-7\nData\naccess\ncontrol")
Motivation_Requirement("INFO8SecureDataTransmission", "=INFO-8\nSecure\nData\nTransmission")
Motivation_Requirement("AUTH3Priorityofuserdatabases", "=AUTH-3\nPriority\nof\nuser\ndatabases")
Motivation_Requirement("INFO6SecureDataStorage", "=INFO-6\nSecure\nData\nStorage")
Motivation_Requirement("ARCH113FeaturesandUserstories", "=ARCH-1.1.3\nFeatures\nand\nUser\nstories")
Motivation_Requirement("ARCH112Threatmodeling", "=ARCH-1.1.2\nThreat\nmodeling")
Motivation_Requirement("ARCH122ComponentCommunication", "=ARCH-1.2.2\nComponent\nCommunication")
Motivation_Requirement("ARCH123AuthenticationMechanism", "=ARCH-1.2.3\nAuthentication\nMechanism")
Motivation_Requirement("ARCH144AccessControlMechanism", "=ARCH-1.4.4\nAccess\nControl\nMechanism")
Motivation_Requirement("ARCH171Logging", "=ARCH-1.7.1\nLogging")
Motivation_Requirement("ARCH1112Unsynchronizedstate", "=ARCH-1.11.2\nUnsynchronized\nstate")
Motivation_Requirement("ARCH1141Segregation", "=ARCH-1.14.1\nSegregation")
Motivation_Requirement("ARCH162Keyprotection", "=ARCH-1.6.2\nKey\nprotection")
Motivation_Requirement("ARCH163Keyreplacement", "=ARCH-1.6.3\nKey\nreplacement")
Motivation_Requirement("ARCH116DesignandArchitectSecurityIn", "=ARCH-1.1.6\nDesign\nand\nArchitect\nSecurity\nIn")
Motivation_Requirement("ARCH111SDLC", "=ARCH-1.1.1\nSDLC")
Motivation_Requirement("ARCH124Authenticationpaths", "=ARCH-1.2.4\nAuthentication\npaths")
Motivation_Requirement("ARCH141AccessEnforcementPoints", "=ARCH-1.4.1\nAccess\nEnforcement\nPoints")
Motivation_Requirement("ARCH152Serialization", "=ARCH-1.5.2\nSerialization")
Motivation_Requirement("ARCH153Inputvalidation", "=ARCH-1.5.3\nInput\nvalidation")
Motivation_Requirement("ARCH154Outputencoding", "=ARCH-1.5.4\nOutput\nencoding")
Motivation_Requirement("ARCH1113ThreadSafe", "=ARCH-1.11.3\nThread\nSafe")
Motivation_Requirement("SDLC4Documenthighlevelarchitectureandthreatmodel", "=SDLC4\n-\nDocument\nhigh\nlevel\narchitecture\nand\nthreat\nmodel")
Motivation_Requirement("ARCH191CommunicationProtection", "=ARCH-1.9.1\nCommunication\nProtection")
Motivation_Requirement("INFO3LocalDatastore", "=INFO-3\nLocal\nData\nstore")
Motivation_Requirement("ARCH2Plugins", "=ARCH-2\nPlugins")
Motivation_Requirement("SDLC1BuildSystem", "=SDLC1\n-\nBuild\nSystem")
Motivation_Requirement("SDLC2DependencyManagement", "=SDLC2\n-\nDependency\nManagement")
Motivation_Requirement("SDLC3Technicalsystemdocumentation", "=SDLC3\n-\nTechnical\nsystem\ndocumentation")
Motivation_Requirement("UI1Screenresolutionsandsizes", "=UI1\n-\nScreen\nresolutions\nand\nsizes")
Motivation_Requirement("UI2Platformindependence", "=UI2\n-\nPlatform\nindependence")
Motivation_Requirement("BACK1PlatformSupport", "=BACK1\n-\nPlatform\nSupport")
Rel_Influence("ARCH112Threatmodeling", "ARCH113FeaturesandUserstories")
Rel_Influence("SDLC4Documenthighlevelarchitectureandthreatmodel", "ARCH112Threatmodeling")
Rel_Influence("ARCH113FeaturesandUserstories", "ARCH116DesignandArchitectSecurityIn")
Rel_Influence("ARCH112Threatmodeling", "ARCH116DesignandArchitectSecurityIn")
Rel_Influence("ARCH111SDLC", "ARCH116DesignandArchitectSecurityIn")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH122ComponentCommunication")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH124Authenticationpaths")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH123AuthenticationMechanism")
Rel_Association("ARCH124Authenticationpaths", "ARCH123AuthenticationMechanism")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH141AccessEnforcementPoints")
Rel_Association("ARCH144AccessControlMechanism", "ARCH141AccessEnforcementPoints")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH144AccessControlMechanism")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH152Serialization")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH153Inputvalidation")
Rel_Association("ARCH152Serialization", "ARCH153Inputvalidation")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH154Outputencoding")
Rel_Association("ARCH152Serialization", "ARCH154Outputencoding")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH171Logging")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH1112Unsynchronizedstate")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH1113ThreadSafe")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH1141Segregation")
Rel_Realization("ARCH123AuthenticationMechanism", "AUTH1LocalUserDatabase")
Rel_Influence("INFO6SecureDataStorage", "AUTH1LocalUserDatabase")
Rel_Realization("ARCH123AuthenticationMechanism", "AUTH2Remoteuserdatabase")
Rel_Influence("INFO8SecureDataTransmission", "AUTH2Remoteuserdatabase")
Rel_Association("AUTH1LocalUserDatabase", "AUTH3Priorityofuserdatabases")
Rel_Association("AUTH2Remoteuserdatabase", "AUTH3Priorityofuserdatabases")
Rel_Influence("INFO2Automaticinformationgathering", "INFO1Manualentries")
Rel_Influence("ARCH2Plugins", "INFO1Manualentries")
Rel_Influence("ARCH2Plugins", "INFO2Automaticinformationgathering")
Rel_Influence("INFO5DisableAutomaticInformationGathering", "INFO2Automaticinformationgathering")
Rel_Influence("INFO6SecureDataStorage", "INFO3LocalDatastore")
Rel_Specialization("CI5Mandatoryattributes", "CI1UniqueIdentifier")
Rel_Realization("CI5Mandatoryattributes", "CI2Assettypehierarchy")
Rel_Influence("ARCH2Plugins", "CI2Assettypehierarchy")
Rel_Influence("ARCH2Plugins", "CI3Attributes")
Rel_Specialization("CI3Attributes", "CI4Relationships")
Rel_Specialization("CI3Attributes", "CI5Mandatoryattributes")
Rel_Realization("ARCH171Logging", "CI6AuditLog")
Rel_Influence("CI5Mandatoryattributes", "CI7Customassettypes")
Rel_Realization("INFO2Automaticinformationgathering", "INFO4AutomatedAssetdiscovery")
Rel_Influence("ARCH122ComponentCommunication", "ARCH2Plugins")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH162Keyprotection")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH163Keyreplacement")
Rel_Aggregation("ARCH111SDLC", "SDLC1BuildSystem")
Rel_Aggregation("ARCH111SDLC", "SDLC2DependencyManagement")
Rel_Influence("ARCH116DesignandArchitectSecurityIn", "SDLC3Technicalsystemdocumentation")
Rel_Influence("SDLC4Documenthighlevelarchitectureandthreatmodel", "SDLC3Technicalsystemdocumentation")
Rel_Influence("ARCH124Authenticationpaths", "UI2Platformindependence")
Rel_Influence("ARCH141AccessEnforcementPoints", "UI2Platformindependence")
Rel_Influence("ARCH124Authenticationpaths", "BACK1PlatformSupport")
Rel_Influence("ARCH141AccessEnforcementPoints", "BACK1PlatformSupport")
Rel_Influence("ARCH152Serialization", "INFO6SecureDataStorage")
Rel_Influence("ARCH162Keyprotection", "INFO6SecureDataStorage")
Rel_Influence("ARCH163Keyreplacement", "INFO6SecureDataStorage")
Rel_Realization("ARCH144AccessControlMechanism", "INFO7Dataaccesscontrol")
Rel_Influence("AUTH1LocalUserDatabase", "INFO7Dataaccesscontrol")
Rel_Influence("AUTH2Remoteuserdatabase", "INFO7Dataaccesscontrol")
Rel_Influence("ARCH162Keyprotection", "INFO8SecureDataTransmission")
Rel_Influence("ARCH163Keyreplacement", "INFO8SecureDataTransmission")
Rel_Realization("ARCH191CommunicationProtection", "INFO8SecureDataTransmission")
Rel_Aggregation("ARCH116DesignandArchitectSecurityIn", "ARCH191CommunicationProtection")
Rel_Association("ARCH122ComponentCommunication", "ARCH191CommunicationProtection")
@enduml
    