name: make all-test

on:
  push:
    branches: [ "develop", "ci/cd" ]
  pull_request:
    branches: [ "develop", "ci/cd" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Test
      run: |
        make all-test
        docker-compose -f test-docker-compose.yaml up -d
        docker-compose -f test-docker-compose.yaml run --rm cypress
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          echo "Cypress tests failed with exit code $exit_code"
          exit $exit_code
        fi
